version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Tallinn"
    target-branch: "dependency-update"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Tallinn"
    target-branch: "dependency-update"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      all-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
      include: "scope"
